version: 2
jobs:
  build:
    docker:

      - image: qgis/qgis3-build-deps:latest
        environment:
          DISPLAY: ":99"

    working_directory: /qgis

    steps:

      - checkout

      - run:
          name: Build QGIS
          command: |
            override:
              - >-
              mkdir build
              && cd build
              && cmake
              -GNinja
              -DCMAKE_BUILD_TYPE=Debug
              -DUSE_CCACHE=OFF
              -DWITH_QUICK=ON
              -DWITH_3D=ON
              -DWITH_STAGED_PLUGINS=ON
              -DWITH_GRASS=OFF
              -DSUPPRESS_QT_WARNINGS=ON
              -DENABLE_MODELTEST=ON
              -DENABLE_PGTEST=ON
              -DENABLE_MSSQLTEST=ON
              -DWITH_QSPATIALITE=ON
              -DWITH_QWTPOLAR=OFF
              -DWITH_APIDOC=OFF
              -DWITH_ASTYLE=OFF
              -DWITH_DESKTOP=ON
              -DWITH_BINDINGS=ON
              -DWITH_SERVER=ON
              -DDISABLE_DEPRECATED=ON
              -DWERROR=TRUE
              ..
              && ninja -j 2


